Repository rilling/robocodeFall2024, pull requests merged in 2024-10, with the labels that each got.

#13 Group 9 - Case Study #1
  robocode.api/src/main/java/gl4java/GLFunc.java
  robocode.battle/src/main/java/net/sf/robocode/battle/BaseBattle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/Module.java
  robocode.battle/src/main/java/net/sf/robocode/recording/RecordManager.java
Labels: technical debt, Group 9

#6 Group 11 case study 1
  robocode.battle/src/main/java/net/sf/robocode/battle/BaseBattle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/BattleManager.java
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotStatistics.java
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/TeamPeer.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/BulletSnapshot.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/RobotSnapshot.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/ScoreSnapshot.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
  robocode.battle/src/main/java/net/sf/robocode/recording/BattlePlayer.java
  robocode.battle/src/main/java/net/sf/robocode/recording/BattleRecordInfo.java
  robocode.battle/src/main/java/net/sf/robocode/recording/BattleRecorder.java
  robocode.battle/src/main/java/net/sf/robocode/recording/RecordManager.java
Labels: technical debt, Group 11

#17 Group 12 - Case Study 1
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/CompilerPreferencesDialog.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/CompilerProperties.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/EditWindow.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/JavaDocument.java
Labels: technical debt, Group 12

#9 Technical Debt Fixes for Case Study 1 - Group 10
  robocode.api/src/main/java/net/sf/robocode/io/FileUtil.java
  robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
Labels: technical debt, Group 10

#20 SOEN 6431 - Fall 2024 - Group 14
  robocode.repository/src/main/java/net/sf/robocode/repository/items/RepositoryItem.java
  robocode.repository/src/main/java/net/sf/robocode/repository/items/RobotItem.java
  robocode.repository/src/main/java/net/sf/robocode/repository/parsers/ClasspathFileParser.java
  robocode.repository/src/main/java/net/sf/robocode/repository/root/handlers/JarHandler.java
Labels: technical debt, Group 14

#19 Additional Group 9 PR for missing member contributions
  robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
  robocode.battle/src/main/java/net/sf/robocode/recording/RecordManager.java
Labels: technical debt, Group 9

#21 Fix failing build because of sonarqube plugin in gradle build file
  build.gradle.kts
  buildSrc/build.gradle.kts
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/CompilerPreferencesDialog.java
Labels: bug
