Repository rilling/robocodeFall2024, pull requests merged in 2024-11, with the labels that each got.

#51 Group 11 Case Study 2
  robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
Labels: Group 11, Removing Software Clones

#32 Group 12 - Changes for Case Study 2
  .idea/jarRepositories.xml
  .idea/kotlinc.xml
  .idea/vcs.xml
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/LineHighlighter.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/RobocodeEditor.java
Labels: Group 12, Removing Software Clones

#72 Group #15 : Case Study 2 - Remove Clones
  .idea/ClojureProjectResolveSettings.xml
  robocode.api/src/main/java/net/sf/robocode/serialization/RbSerializer.java
  robocode.api/src/main/java/robocode/DeathEvent.java
  robocode.api/src/main/java/robocode/KeyPressedEvent.java
  robocode.api/src/main/java/robocode/KeyReleasedEvent.java
  robocode.api/src/main/java/robocode/KeyTypedEvent.java
  robocode.api/src/main/java/robocode/MouseClickedEvent.java
  robocode.api/src/main/java/robocode/MouseDraggedEvent.java
  robocode.api/src/main/java/robocode/MouseEnteredEvent.java
  robocode.api/src/main/java/robocode/MouseEventSerializer.java
  robocode.api/src/main/java/robocode/MouseExitedEvent.java
  robocode.api/src/main/java/robocode/MouseMovedEvent.java
  robocode.api/src/main/java/robocode/MousePressedEvent.java
  robocode.api/src/main/java/robocode/MouseReleasedEvent.java
  robocode.api/src/main/java/robocode/Robot.java
  robocode.api/src/main/java/robocode/WinEvent.java
Labels: Group 15, Removing Software Clones

#74 Group 14 Case Study 2
  robocode.repository/src/main/java/net/sf/robocode/repository/items/RobotItem.java
  robocode.repository/src/main/java/net/sf/robocode/repository/items/RobotSpecItem.java
  robocode.repository/src/main/java/net/sf/robocode/repository/packager/JarCreator.java
  robocode.repository/src/main/java/net/sf/robocode/repository/packager/JarExtractor.java
  robocode.repository/src/main/java/net/sf/robocode/repository/root/handlers/RootHandler.java
  robocode.tests.robots/src/main/java/tested/robots/RadarTurnRateAndSetAdjust.java
  robocode.ui/src/main/java/net/sf/robocode/ui/dialog/WindowPositionManager.java
Labels: Group 14, Removing Software Clones

#75 Group 9 - Case study #2 changes
  robocode.battle/src/main/java/net/sf/robocode/battle/BattleManager.java
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotStatistics.java
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/TeamPeer.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/BulletSnapshot.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/ScoreSnapshot.java
Labels: Group 9, Removing Software Clones

#76 Group 9 - Updated member contribution
  robocode.battle/src/main/java/net/sf/robocode/battle/BaseBattle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/BattleManager.java
  robocode.battle/src/main/java/net/sf/robocode/battle/IBattle.java
Labels: Group 9, Removing Software Clones

#77 Group 10 - Case Study 2
  robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/ScoreSnapshot.java
  robocode.ui/src/main/java/net/sf/robocode/ui/CheckList.java
Labels: Group 10, Removing Software Clones

#87 Group 11 Case Study 3
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
  robocode.host/src/main/java/net/sf/robocode/host/io/RobotFileSystemManager.java
  robocode.repository/src/main/java/net/sf/robocode/repository/packager/JarExtractor.java
Labels: Group 11, Remove Software Vulnerability

#89 Group 12 - Case Study 3 changes
  robocode.installer/src/main/java/net/sf/robocode/installer/AutoExtract.java
  robocode.repository/src/main/java/net/sf/robocode/repository/packager/JarExtractor.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/EditorPane.java
  robocode.ui/src/main/java/net/sf/robocode/ui/battleview/BattleView.java
Labels: Group 12, Remove Software Vulnerability
